# Generated by Django 3.2.9 on 2024-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='displayname',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
