# Generated by Django 3.2.9 on 2021-12-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(help_text='Required. example: jon.doe@email.com', max_length=254),
        ),
    ]
