# Generated by Django 3.2.9 on 2022-01-11 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0002_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_picture'),
        ),
    ]
