# Generated by Django 3.2.9 on 2024-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0005_alter_productmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.URLField(help_text='this needs to the cloudinary url which represents the desired image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='This needs to the cloudinary url which represents the desired image', max_length=10000000, null=True),
        ),
    ]
