# Generated by Django 3.2.9 on 2024-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0007_orderingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingmodel',
            name='status',
            field=models.CharField(choices=[('1', 'OrderReceived')], default='1', max_length=200),
        ),
    ]
