# Generated by Django 3.2.9 on 2024-05-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0008_alter_orderingmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingmodel',
            name='status',
            field=models.CharField(choices=[('1', 'OrderReceived'), ('2', 'Processing'), ('3', 'Delivery'), ('4', 'Issue')], default='1', max_length=200),
        ),
    ]
