# Generated by Django 3.2.9 on 2024-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0011_auto_20240602_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='short_descriptions',
            field=models.CharField(blank=True, default='This is a shortdescription of a webshop product', max_length=402),
        ),
    ]
