# Generated by Django 3.2.9 on 2024-06-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop_app', '0012_productmodel_short_descriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
    ]
