name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./smarthome-webshop -t bruderjarck/smarthome-frontend -f ./smarthome-webshop/Dockerfile .
      
    - name: Login to docerhub
      env:
        DOCKER_HUB_API_KEY: ${{ secrets.DOCKER_HUB_API_KEY }}
      run: docker login -u "bruderjarck" -p "$DOCKER_HUB_API_KEY" docker.io
      
    - name: Upload to docerhub
      run: docker push bruderjarck/smarthome-frontend:latest
      
    - name: Install and configure the Koyeb CLI
      uses: koyeb-community/install-koyeb-cli@v2
      with:
          api_token: "${{ secrets.KOYEB_API_KEY }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          
    - name: Deploy to Koyeb
      run: koyeb service redeploy mild-eadie/smarthome-frontend
      
